"""Plugin lifecycle, config, data, resources and view errors for the Launcher management API.

Extracted verbatim from ``launcher_main._start_management_server`` -- method
bodies are byte-identical to the original, only re-indented, so this is a pure
move.  See ``management_api/__init__.py`` for the composed handler.

Shared launcher registries are imported **by value** from ``launcher_main``.
That is safe because launcher_main only ever mutates these containers in place
(``dict[...] = ...`` / ``.append`` / ``.add``); the single rebind of
``_BUILTIN_PLUGINS`` happens at launcher_main module load, i.e. before this
module can be imported -- ``launcher_main`` imports this package lazily, from
inside the function that starts the server.
"""

from __future__ import annotations

import base64
import io
import json
import os
import re
import shutil
import sys
import time
import zipfile

from opensquad.launcher.process_manager import AgentProcess
from opensquad.launcher_main import (
    _BUILTIN_PLUGINS,
    AGENTS_DIR,
    BUILTIN_PLUGINS_DIR,
    PLUGINS_DIR,
    PROJECT_ROOT,
    SKILLS_DIR,
    _abspath_under,
    _collect_plugin_dirs,
    _is_bundled_resource,
    _log,
    _processes,
    _refresh_builtin_plugins,
    _resolve_plugin_dir,
    discover_agents,
    ensure_plugin_service_registered,
    plan_resource_uninstall,
)
from opensquad.system_config import syscfg


class PluginsMixin:
    """Plugin lifecycle, config, data, resources and view errors."""

    _skipped_dirs: set = set()

    def _handle_create(self, body: dict):
        """Create a new agent directory"""
        name = (body.get("name") or "").strip()
        if not name:
            return self._send_json({"error": "Missing 'name'"}, 400)
        # Security check: only allow alphanumeric and underscore
        if not all(c.isalnum() or c == "_" for c in name):
            return self._send_json({"error": "Name must be alphanumeric/underscore"}, 400)
        agent_dir = os.path.join(AGENTS_DIR, name)
        if os.path.exists(agent_dir):
            return self._send_json({"error": f"Agent '{name}' already exists"}, 400)

        # Support externally supplied agent_id (6-digit numeric ID generated by routes.py)
        # Fall back to old format "{name}-001" if not provided
        agent_id = body.get("agent_id", f"{name}-001")

        # Group chat account credentials (generated and passed in by routes.py)
        chat_email = body.get("chat_email", "") or "ai@ai"
        chat_password = body.get("chat_password", "") or "aaaaaa"

        os.makedirs(agent_dir, exist_ok=True)
        # Create default config.json
        default_config = {
            "agent_id": agent_id,
            "agent_name": body.get("agent_name", name),
            "agent_type": body.get("agent_type", "general"),
            "description": body.get("description", ""),
            "capabilities": [],
            "model": {
                "api_protocol": "openai_compat",  # Default: OpenAI-compatible API (most third-party providers)
                "provider": "",
                "api_key": "",
                "base_url": "",
                "model_name": "",
                "tool_call_mode": "native",  # Default: Native FC (forced) — use native function calling
                "tool_filter": "high",  # Default: load common tools (97) — balance between features and performance
            },
            "tools": [
                "system",
                "filesystem",
                "agent_setup",
                "im",
                "collaboration",
                "delegate_task",
                "workspace",
                "task_watch",
                "websearch",
                "reminder",
                "vision",
                "mcp_query",
                "plugin_admin",
            ],
            "group_chat": {
                "enabled": True,
                "email": chat_email,
                "password": chat_password,
                "groups": [],
            },
            "web_server": {"enabled": True},
            "gateway": {"enabled": True, "url": syscfg.gateway_register_url()},
            "prompt": {"role": "role.md"},
            "mcp": {"enabled": True},  # Default: MCP enabled; specific services are controlled in mcp_config.json
            "skills": {
                "enabled": True,
                "active": [],
            },  # Default: skills enabled; public skill library auto-discovered
        }
        with open(os.path.join(agent_dir, "config.json"), "w", encoding="utf-8") as f:
            json.dump(default_config, f, ensure_ascii=False, indent=2)

        # Create Agent-specific MCP config — copy from central config if it exists
        central_mcp_path = syscfg.workspace_data_dir("mcp_config.json")
        if os.path.isfile(central_mcp_path):
            try:
                with open(central_mcp_path, encoding="utf-8") as f:
                    default_mcp_config = json.load(f)
            except Exception:
                default_mcp_config = None
        else:
            default_mcp_config = None
        if not default_mcp_config or "mcpServers" not in default_mcp_config:
            default_mcp_config = {
                "mcpServers": {
                    "filesystem": {
                        "enabled": True,
                        "command": "npx",
                        "args": ["-y", "@modelcontextprotocol/server-filesystem", "."],
                        "timeout": 30,
                    },
                    "sequential-thinking": {
                        "enabled": True,
                        "command": "npx",
                        "args": ["-y", "@langgpt/sequential-thinking-mcp"],
                        "timeout": 30,
                    },
                    "windows-cli": {
                        "enabled": True,
                        "command": "npx",
                        "args": ["-y", "@simonb97/server-win-cli"],
                        "timeout": 30,
                        "autoApprove": ["execute_command"],
                    },
                    "playwright": {
                        "enabled": True,
                        "command": "npx",
                        "args": ["-y", "@playwright/mcp"],
                        "timeout": 60,
                        "autoApprove": [
                            "browser_navigate",
                            "browser_snapshot",
                            "browser_click",
                            "browser_screenshot",
                            "browser_type",
                            "browser_evaluate",
                            "browser_take_screenshot",
                        ],
                    },
                    "chrome-devtools": {
                        "enabled": False,
                        "command": "npx",
                        "args": ["chrome-devtools-mcp@latest"],
                        "timeout": 30,
                        "autoApprove": ["start_browser"],
                    },
                    "github": {
                        "enabled": False,
                        "command": "npx",
                        "args": ["-y", "@modelcontextprotocol/server-github"],
                        "timeout": 30,
                        "env": {"GITHUB_PERSONAL_ACCESS_TOKEN": ""},
                    },
                    "zai-mcp-server": {
                        "enabled": False,
                        "command": "npx",
                        "args": ["-y", "@z_ai/mcp-server"],
                        "timeout": 60,
                        "env": {"Z_AI_API_KEY": "", "Z_AI_MODE": "ZHIPU"},
                    },
                }
            }
        with open(os.path.join(agent_dir, "mcp_config.json"), "w", encoding="utf-8") as f:
            json.dump(default_mcp_config, f, ensure_ascii=False, indent=2)

        # Create empty role.md
        with open(os.path.join(agent_dir, "role.md"), "w", encoding="utf-8") as f:
            f.write(f"# {body.get('agent_name', name)}\n\nWrite the role definition here.\n")

        return self._send_json(
            {
                "message": f"Agent '{name}' created",
                "dir": name,
                "mcp_config": "Created with lightweight services enabled (filesystem, sequential-thinking, windows-cli)",
            }
        )

    def _handle_rescan(self):
        """Re-scan the agents/ directory to discover new agents"""
        all_discovered = discover_agents(AGENTS_DIR)
        new_count = 0
        for info in all_discovered:
            if info["name"] not in _processes:
                ap = AgentProcess(info["dir"], info["config"])
                _processes[info["name"]] = ap
                new_count += 1
        return self._send_json({"message": f"Rescan complete, {new_count} new agent(s) found"})

    def _handle_delete(self, name: str):
        """Delete agent: stop process first, then delete directory and remove from process table"""
        # Security check: only allow alphanumeric and underscore
        if not all(c.isalnum() or c == "_" for c in name):
            return self._send_json({"error": "Invalid agent name"}, 400)

        agent_dir = os.path.join(AGENTS_DIR, name)
        if not os.path.isdir(agent_dir):
            return self._send_json({"error": f"Agent '{name}' not found"}, 404)

        # Stop process if it is running
        if name in _processes:
            ap = _processes[name]
            if ap.is_alive():
                ap.stop()
            del _processes[name]

        # Delete directory
        try:
            shutil.rmtree(agent_dir)
        except Exception as e:
            return self._send_json({"error": f"Failed to delete directory: {e}"}, 500)

        return self._send_json({"message": f"Agent '{name}' deleted"})

    def _handle_install_zip_plugin(self, body: dict):
        """
        POST /api/plugins/install-zip
        Receive a plugin zip broadcast from Gateway and extract/install to the local plugins/ directory.
        Request body: { "plugin_id": str, "zip_b64": str (base64-encoded zip content) }
        """
        plugin_id = (body.get("plugin_id") or "").strip()
        zip_b64 = body.get("zip_b64", "")
        if not plugin_id or not zip_b64:
            return self._send_json({"error": "plugin_id and zip_b64 are required"}, 400)

        try:
            zip_bytes = base64.b64decode(zip_b64)
        except Exception as e:
            return self._send_json({"error": f"Invalid base64: {e}"}, 400)

        plugin_dest = os.path.join(PLUGINS_DIR, plugin_id)
        existing_manifest = os.path.join(plugin_dest, "plugin.json")
        existing_plugin_py_path = os.path.join(plugin_dest, "plugin.py")

        # Preserve existing enabled state and plugin.py
        existing_enabled = True
        existing_version = None
        existing_category = None
        existing_plugin_py: bytes | None = None
        if os.path.isfile(existing_manifest):
            try:
                with open(existing_manifest, encoding="utf-8") as f:
                    existing_data = json.load(f)
                existing_enabled = existing_data.get("enabled", True)
                existing_version = existing_data.get("version")
                existing_category = existing_data.get("category")
            except Exception:
                pass
        if os.path.isfile(existing_plugin_py_path):
            try:
                with open(existing_plugin_py_path, "rb") as f:
                    existing_plugin_py = f.read()
            except Exception:
                pass

        # Extract zip
        os.makedirs(PLUGINS_DIR, exist_ok=True)
        try:
            buf = io.BytesIO(zip_bytes)
            with zipfile.ZipFile(buf) as zf:
                for member in zf.infolist():
                    parts = member.filename.split("/")
                    relative = "/".join(parts[1:]) if len(parts) > 1 else parts[0]
                    if not relative:
                        continue
                    dest_path = os.path.join(plugin_dest, relative)
                    if not os.path.abspath(dest_path).startswith(os.path.abspath(plugin_dest)):
                        continue
                    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
                    if not member.is_dir():
                        with zf.open(member) as src, open(dest_path, "wb") as dst:
                            shutil.copyfileobj(src, dst)
        except zipfile.BadZipFile as e:
            return self._send_json({"error": f"Invalid zip archive: {e}"}, 422)
        except Exception as e:
            return self._send_json({"error": f"Failed to extract plugin: {e}"}, 500)

        # Restore plugin.py
        if existing_plugin_py is not None:
            try:
                with open(existing_plugin_py_path, "wb") as f:
                    f.write(existing_plugin_py)
            except Exception as e:
                _log.warning(f"[Launcher] Warning: Failed to restore plugin.py for '{plugin_id}': {e}")

        # Restore enabled state and category
        if os.path.isfile(existing_manifest):
            try:
                with open(existing_manifest, encoding="utf-8") as f:
                    new_manifest = json.load(f)
                new_manifest["enabled"] = existing_enabled
                # Restore category only if the new zip does not carry one
                if existing_category and not new_manifest.get("category"):
                    new_manifest["category"] = existing_category
                with open(existing_manifest, "w", encoding="utf-8") as f:
                    json.dump(new_manifest, f, indent=2, ensure_ascii=False)
            except Exception as e:
                _log.warning(f"[Launcher] Warning: Failed to restore enabled state for '{plugin_id}': {e}")

        # Trigger hot-reload
        try:
            reload_ts_path = os.path.join(PLUGINS_DIR, ".reload_ts")
            with open(reload_ts_path, "w") as f:
                f.write(str(time.time()))
        except Exception as e:
            _log.warning(f"[Launcher] Warning: Failed to write .reload_ts: {e}")

        action = "updated" if existing_version else "installed"
        try:
            from opensquad._syscfg._workspace import clear_locally_uninstalled

            clear_locally_uninstalled("plugins", plugin_id)
        except Exception:
            pass
        _log.info(f"[Launcher] Plugin '{plugin_id}' {action} via broadcast zip install")
        return self._send_json({"ok": True, "action": action, "plugin_id": plugin_id})

    def _find_plugin_dir(self, name: str):
        """
        Resolve a plugin name to its directory path.

        Tries two strategies:
        1. Direct match: dir/name exists as a directory with plugin.py
        2. Name field match: scan all plugin dirs, find one where plugin.json["name"] == name

        Returns (plugin_dir, dir_name) tuple, or (None, None) if not found.
        """
        return _resolve_plugin_dir(name)

    def _writable_plugin_json_path(self, name: str) -> tuple[str, str] | tuple[None, None]:
        """Return (plugin_json_path, dir_name) under workspace for writes."""
        plugin_dir, dir_name = self._find_plugin_dir(name)
        if not dir_name:
            return None, None
        writable_dir = os.path.join(PLUGINS_DIR, dir_name)
        os.makedirs(writable_dir, exist_ok=True)
        return os.path.join(writable_dir, "plugin.json"), dir_name

    def _handle_list_plugins(self):
        """Scan plugins/ directory, read plugin.json for each, return list."""
        plugins = []
        plugin_dirs = _collect_plugin_dirs()
        if not plugin_dirs:
            return self._send_json({"plugins": []})
        builtin_reg = _refresh_builtin_plugins()

        for name in sorted(plugin_dirs):
            plugin_dir = plugin_dirs[name]
            plugin_json_path = os.path.join(plugin_dir, "plugin.json") if os.path.isdir(plugin_dir) else ""
            if os.path.isfile(plugin_json_path):
                try:
                    with open(plugin_json_path, encoding="utf-8") as f:
                        meta = json.load(f)
                except Exception:
                    meta = {}
            else:
                meta = {}

            is_builtin = name in builtin_reg
            bundled = _is_bundled_resource(plugin_dir, PLUGINS_DIR, BUILTIN_PLUGINS_DIR)

            # For built-in plugins without a plugin.json, enforce default enabled state
            if is_builtin and not meta:
                bp_cfg = _BUILTIN_PLUGINS[name]
                meta["enabled"] = bp_cfg.get("default_enabled", True)

            plugins.append(
                {
                    "name": meta.get("name", name),
                    "dir_name": name,
                    "display_name": meta.get("display_name", name),
                    "version": meta.get("version", "0.0.0"),
                    "type": meta.get("type", "tool"),
                    "enabled": meta.get("enabled", True),
                    "description": meta.get("description", ""),
                    "author": meta.get("author", ""),
                    "tags": meta.get("tags", []),
                    "category": meta.get("category", ""),
                    "tools": meta.get("tools", []),
                    "hooks": meta.get("hooks", []),
                    "config": meta.get("config", {}),
                    "config_schema": meta.get("config_schema", {}),
                    "contributes": meta.get("contributes", {}),
                    "dependencies": meta.get("dependencies", {}),
                    "service": meta.get("service"),
                    "service_only": meta.get("service_only", False),
                    "service_toggle": meta.get("service_toggle", False),
                    "builtin": is_builtin,
                    "bundled": bundled,
                }
            )

        return self._send_json({"plugins": plugins})

    def _handle_plugin_set_enabled(self, name: str, enabled: bool):
        """Set plugin enabled/disabled by updating plugin.json."""
        plugin_dir, dir_name = self._find_plugin_dir(name)
        if not plugin_dir or not dir_name:
            return self._send_json({"error": f"Plugin '{name}' not found"}, 404)

        plugin_json_path, _ = self._writable_plugin_json_path(name)
        if not plugin_json_path:
            return self._send_json({"error": f"Plugin '{name}' not found"}, 404)

        if os.path.isfile(plugin_json_path):
            try:
                with open(plugin_json_path, encoding="utf-8") as f:
                    meta = json.load(f)
            except Exception:
                meta = {}
        else:
            src_manifest = os.path.join(plugin_dir, "plugin.json")
            meta = {"name": name}
            if os.path.isfile(src_manifest):
                try:
                    with open(src_manifest, encoding="utf-8") as f:
                        meta = json.load(f)
                except Exception:
                    meta = {"name": name}

        # service_only plugins cannot be enabled — they have no agent tools
        if enabled and meta.get("service_only"):
            return self._send_json({"error": f"Plugin '{name}' is service_only and cannot be enabled"}, 400)

        meta["enabled"] = enabled

        try:
            with open(plugin_json_path, "w", encoding="utf-8") as f:
                json.dump(meta, f, indent=2, ensure_ascii=False)
        except Exception as e:
            return self._send_json({"error": f"Failed to write plugin.json: {e}"}, 500)

        # Sync service_toggle plugins to system_config.json services.{name}.enabled
        if meta.get("service_toggle"):
            try:
                sys_cfg_path = syscfg.workspace_config_path()
                with open(sys_cfg_path, encoding="utf-8") as f:
                    full_cfg = json.load(f)
                if "services" not in full_cfg:
                    full_cfg["services"] = {}
                if name not in full_cfg["services"]:
                    full_cfg["services"][name] = {}
                full_cfg["services"][name]["enabled"] = enabled
                with open(sys_cfg_path, "w", encoding="utf-8") as f:
                    json.dump(full_cfg, f, indent=2, ensure_ascii=False)
                # Invalidate system_config cache
                from opensquad import system_config as _syscfg_mod

                _syscfg_mod._cache = None
                _log.info(f"[Launcher] Synced services.{name}.enabled = {enabled}")
            except Exception as e:
                _log.warning(f"[Launcher] Warning: Failed to sync services config: {e}")

        # Write reload signal file so running agents detect the change
        try:
            reload_ts_path = os.path.join(PLUGINS_DIR, ".reload_ts")
            with open(reload_ts_path, "w") as f:
                f.write(str(time.time()))
        except Exception as e:
            _log.warning(f"[Launcher] Warning: Failed to write .reload_ts: {e}")

        # Auto-start/stop service for service_toggle plugins
        if meta.get("service_toggle"):
            psp = ensure_plugin_service_registered(name)
            if psp is not None:
                if enabled:
                    # Start service if not running
                    if not psp.is_alive():
                        service_cfg = meta.get("service", {})
                        if service_cfg.get("auto_start"):
                            _log.info(f"[Launcher] Auto-starting plugin service: {name}")
                            psp.start()
                else:
                    # Stop service if running
                    if psp.is_alive():
                        _log.info(f"[Launcher] Stopping plugin service: {name}")
                        psp.stop()

        action = "enabled" if enabled else "disabled"
        return self._send_json({"ok": True, "message": f"Plugin '{name}' {action}"})

    def _handle_get_plugin_config(self, name: str):
        """GET /api/plugins/{name}/config - Return config values + schema."""
        plugin_dir, _dir_name = self._find_plugin_dir(name)
        if not plugin_dir:
            return self._send_json({"error": f"Plugin '{name}' not found"}, 404)

        # Read config_schema and config.section from plugin.json
        plugin_json_path = os.path.join(plugin_dir, "plugin.json")
        schema = {}
        section = None
        plugin_type = "tool"
        if os.path.isfile(plugin_json_path):
            try:
                with open(plugin_json_path, encoding="utf-8") as f:
                    meta = json.load(f)
                schema = meta.get("config_schema", {})
                section = meta.get("config", {}).get("section")
                plugin_type = meta.get("type", "tool")
            except Exception:
                pass

        # Platform plugins (telegram/feishu/qq etc.) bridge to system_config.json.
        # Tool/hook plugins always use data/plugins/{name}/config.json.
        if section and plugin_type == "platform":
            try:
                sys_cfg_path = syscfg.workspace_config_path()
                with open(sys_cfg_path, encoding="utf-8") as f:
                    full_cfg = json.load(f)
                sec_data = full_cfg.get(section, {})
                values = {
                    "service_enabled": full_cfg.get("services", {}).get(section, {}).get("enabled", False),
                    "bots": sec_data.get("bots", []),
                }
            except Exception:
                values = {}
        else:
            # Read persisted config values from data/plugins/{name}/config.json
            config_path = syscfg.workspace_data_dir("plugins", name, "config.json")
            values = {}
            if os.path.isfile(config_path):
                try:
                    with open(config_path, encoding="utf-8") as f:
                        values = json.load(f)
                except Exception:
                    pass

        # Merge defaults from schema for any missing keys
        merged = {}
        for key, field_schema in schema.items():
            if isinstance(field_schema, dict):
                default_val = field_schema.get("default")
                if key == "bots":
                    # bot_list: default to empty list, not None
                    merged[key] = values.get(key, default_val if default_val is not None else [])
                else:
                    merged[key] = values.get(key, default_val)
            else:
                merged[key] = values.get(key)

        return self._send_json(
            {
                "name": name,
                "config_schema": schema,
                "config": merged,
            }
        )

    def _handle_put_plugin_config(self, name: str, body: dict):
        """PUT /api/plugins/{name}/config - Save config values."""
        plugin_dir, _dir_name = self._find_plugin_dir(name)
        if not plugin_dir:
            return self._send_json({"error": f"Plugin '{name}' not found"}, 404)

        config_values = body.get("config", body)

        # Check if this plugin bridges to system_config.json (platform plugins only)
        plugin_json_path = os.path.join(plugin_dir, "plugin.json")
        section = None
        plugin_type = "tool"
        if os.path.isfile(plugin_json_path):
            try:
                with open(plugin_json_path, encoding="utf-8") as f:
                    meta = json.load(f)
                section = meta.get("config", {}).get("section")
                plugin_type = meta.get("type", "tool")
            except Exception:
                pass

        if section and plugin_type == "platform":
            try:
                sys_cfg_path = syscfg.workspace_config_path()
                with open(sys_cfg_path, encoding="utf-8") as f:
                    full_cfg = json.load(f)
                # Update bots list under the section key
                if section not in full_cfg:
                    full_cfg[section] = {}
                if "bots" in config_values:
                    full_cfg[section]["bots"] = config_values["bots"]
                # Update service enabled flag
                if "service_enabled" in config_values:
                    if "services" not in full_cfg:
                        full_cfg["services"] = {}
                    if section not in full_cfg["services"]:
                        full_cfg["services"][section] = {}
                    full_cfg["services"][section]["enabled"] = config_values["service_enabled"]
                    # Also sync plugin.json enabled field for UI consistency
                    if meta.get("service_toggle"):
                        meta["enabled"] = config_values["service_enabled"]
                        try:
                            with open(plugin_json_path, "w", encoding="utf-8") as f:
                                json.dump(meta, f, indent=2, ensure_ascii=False)
                        except Exception as e:
                            _log.warning(f"[Launcher] Warning: Failed to sync plugin.json enabled: {e}")
                with open(sys_cfg_path, "w", encoding="utf-8") as f:
                    json.dump(full_cfg, f, indent=2, ensure_ascii=False)
                # Invalidate system_config module cache so other code sees new values
                from opensquad import system_config as _syscfg_mod

                _syscfg_mod._cache = None
            except Exception as e:
                return self._send_json({"error": f"Failed to write system config: {e}"}, 500)
        else:
            # Persist to data/plugins/{name}/config.json
            config_dir = syscfg.workspace_data_dir("plugins", name)
            config_path = os.path.join(config_dir, "config.json")
            try:
                os.makedirs(config_dir, exist_ok=True)
                with open(config_path, "w", encoding="utf-8") as f:
                    json.dump(config_values, f, indent=2, ensure_ascii=False)
            except Exception as e:
                return self._send_json({"error": f"Failed to write config: {e}"}, 500)

        # Write reload signal so agents pick up new config
        try:
            reload_ts_path = os.path.join(PLUGINS_DIR, ".reload_ts")
            with open(reload_ts_path, "w") as f:
                f.write(str(time.time()))
        except Exception:
            pass

        return self._send_json({"ok": True, "message": f"Config saved for '{name}'"})

    def _handle_get_plugin_data(self, name: str, qs: dict):
        """
        GET /api/plugins/{name}/data - Dynamic plugin data query.

        Convention: if plugins/{name}/query.py exists and exports
        ``query_data(project_root: str, params: dict) -> dict``,
        it will be called automatically. No per-plugin hardcoding needed.
        """
        # Validate plugin exists
        plugin_dir, _dir_name = self._find_plugin_dir(name)
        if not plugin_dir:
            return self._send_json({"error": f"Plugin '{name}' not found"}, 404)

        # Check for query module
        query_module_path = os.path.join(plugin_dir, "query.py")
        if not os.path.isfile(query_module_path):
            return self._send_json({"error": f"Plugin '{name}' has no data query module (query.py)"}, 404)

        # Dynamic import
        import importlib

        module_name = f"plugins.{name}.query"
        try:
            # Reload if already imported (supports hot-reload of query logic)
            if module_name in sys.modules:
                mod = importlib.reload(sys.modules[module_name])
            else:
                mod = importlib.import_module(module_name)
        except Exception as e:
            return self._send_json({"error": f"Failed to import {module_name}: {e}"}, 500)

        if not hasattr(mod, "query_data"):
            return self._send_json({"error": f"Plugin '{name}' query.py missing query_data() function"}, 400)

        # Flatten query-string params: {k: [v1]} -> {k: v1}
        params = {k: v[0] if isinstance(v, list) and v else v for k, v in qs.items()}

        try:
            result = mod.query_data(PROJECT_ROOT, params)
            return self._send_json(result)
        except Exception as e:
            return self._send_json({"error": f"Query failed: {e}"}, 500)

    def _handle_plugin_view_error(self, body: dict):
        """
        POST /api/plugin-view-error
        Append a frontend plugin-view runtime error to
        plugins/{name}/view_errors.log so the agent can read it.
        """
        import datetime as _dt

        plugin_name = body.get("plugin_name", "unknown")
        view_key = body.get("view_key", "")
        error_msg = body.get("error", "")
        stack = body.get("stack", "")

        log_path = os.path.join(PLUGINS_DIR, plugin_name, "view_errors.log")
        try:
            os.makedirs(os.path.dirname(log_path), exist_ok=True)
            ts = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            entry = f"[{ts}] view={view_key}\n  error: {error_msg}\n  stack: {stack[:800]}\n{'─' * 60}\n"
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(entry)
            return self._send_json({"ok": True, "log": log_path})
        except Exception as e:
            return self._send_json({"ok": False, "error": str(e)}, 500)

    def _handle_resource_upload(self, body: dict):
        """
        POST /api/resources/upload
        Saves base64 encoded files to a local resource directory (skills/plugins).
        """
        resource_type = body.get("resource_type")
        files = body.get("files", [])

        if resource_type == "skills":
            base_dir = SKILLS_DIR
        elif resource_type == "plugins":
            base_dir = PLUGINS_DIR
        else:
            return self._send_json({"error": "Invalid resource type"}, 400)

        if not files:
            return self._send_json({"error": "No files provided"}, 400)

        try:
            os.makedirs(base_dir, exist_ok=True)
            # Group files by their top-level directory name to identify the resource name
            resource_names = set()

            for f in files:
                file_path = f.get("filename", "")
                content_b64 = f.get("content", "")
                if not file_path or not content_b64:
                    continue

                parts = file_path.replace("\\", "/").split("/")
                if len(parts) > 1:
                    resource_names.add(parts[0])

                target_path = os.path.join(base_dir, file_path)
                os.makedirs(os.path.dirname(target_path), exist_ok=True)

                with open(target_path, "wb") as out_f:
                    out_f.write(base64.b64decode(content_b64))

            if resource_names:
                from opensquad._syscfg._workspace import clear_locally_uninstalled

                for resource_name in resource_names:
                    clear_locally_uninstalled(resource_type, resource_name)

            # Trigger reload for plugins
            if resource_type == "plugins" and resource_names:
                reload_ts_path = os.path.join(base_dir, ".reload_ts")
                with open(reload_ts_path, "w") as rf:
                    rf.write(str(time.time()))

            return self._send_json(
                {
                    "success": True,
                    "message": f"Successfully uploaded {len(files)} files to {resource_type}",
                    "resources": list(resource_names),
                }
            )
        except Exception as e:
            return self._send_json({"error": str(e)}, 500)

    def _handle_delete_resource(self, resource_type: str, name: str):
        """
        DELETE /api/resources/{type}/{name}

        Removes a workspace overlay when present, then hides the resource in
        this workspace. Bundled seeds under src/plugins or src/skills are
        not deleted. The UI may pass plugin.json ``name`` (whisper_transcribe)
        which differs from the on-disk folder (whisper).
        """
        if not re.match(r"^[a-zA-Z0-9_\-\.]+$", name):
            return self._send_json({"error": "Invalid resource name"}, 400)

        overlay, dir_name, status, err = plan_resource_uninstall(resource_type, name)
        if status != 200 or not dir_name:
            return self._send_json({"error": err}, status)

        base_dir = PLUGINS_DIR if resource_type == "plugins" else SKILLS_DIR
        if overlay:
            if not _abspath_under(overlay, base_dir):
                return self._send_json({"error": "Path traversal detected"}, 400)

        try:

            def _rmtree_onerror(func, path, exc_info):
                import stat as _stat

                try:
                    os.chmod(path, _stat.S_IWRITE)
                except Exception:
                    pass
                try:
                    func(path)
                except Exception:
                    try:
                        import uuid as _uuid

                        dead_name = path + ".dead_" + _uuid.uuid4().hex[:8]
                        os.rename(path, dead_name)
                    except Exception:
                        pass

            if overlay:
                shutil.rmtree(overlay, onerror=_rmtree_onerror)

            from opensquad._syscfg._workspace import mark_locally_uninstalled

            mark_locally_uninstalled(
                "plugins" if resource_type == "plugins" else "skills",
                dir_name,
            )

            if resource_type == "plugins":
                reload_ts_path = os.path.join(base_dir, ".reload_ts")
                try:
                    with open(reload_ts_path, "w") as rf:
                        rf.write(str(time.time()))
                except Exception:
                    pass

            return self._send_json(
                {
                    "ok": True,
                    "message": f"{resource_type[:-1].capitalize()} '{name}' uninstalled",
                    "dir_name": dir_name,
                }
            )
        except Exception as e:
            return self._send_json({"error": f"Failed to delete {resource_type}: {e}"}, 500)

    def _handle_plugin_action(self, name: str, body: dict):
        """
        POST /api/plugins/{name}/action - Execute plugin action.

        Convention: if plugins/{name}/query.py exports
        ``handle_action(project_root: str, action: str, data: dict) -> dict``,
        it will be called automatically.
        """
        # Validate plugin exists
        plugin_dir, _dir_name = self._find_plugin_dir(name)
        if not plugin_dir:
            return self._send_json({"error": f"Plugin '{name}' not found"}, 404)

        # Check for query module with handle_action
        query_module_path = os.path.join(plugin_dir, "query.py")
        if not os.path.isfile(query_module_path):
            return self._send_json({"error": f"Plugin '{name}' does not support actions"}, 400)

        try:
            import importlib.util as _ilu

            spec = _ilu.spec_from_file_location(f"plugins.{name}.query", query_module_path)
            mod = _ilu.module_from_spec(spec)
            spec.loader.exec_module(mod)

            if not hasattr(mod, "handle_action"):
                return self._send_json({"error": f"Plugin '{name}' does not support actions"}, 400)

            action = body.get("action", "")
            data = body.get("data", {})
            result = mod.handle_action(PROJECT_ROOT, action, data)
            return self._send_json(result)
        except Exception as e:
            return self._send_json({"error": f"Action failed: {e}"}, 500)
